site_name: mplchart
site_description: Classic technical analysis stock charts in Python, built on matplotlib
site_url: https://furechan.github.io/mplchart/
site_dir: build/site
repo_url: https://github.com/furechan/mplchart
repo_name: furechan/mplchart

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy

plugins:
  - search
  - mkdocs-jupyter:
      cache_dir: build/cache/mkdocs-jupyter
      execute: false
      include_source: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
