"""Generate Markdown API reference pages from docstrings using griffe.

Renders each module in MODULES to docs/reference/<name>.md and verifies the
result parses cleanly under the same markdown extensions mkdocs uses.
Griffe extracts signatures and google-style docstrings statically into
structured sections; every line of markdown is emitted here.
"""

import re
import sys
from pathlib import Path

import griffe
import markdown

# module path (relative to package) -> (output stem, include class members)
MODULES = {
    "chart": ("chart", True),
    "primitives": ("primitives", False),
    "indicators": ("indicators", False),
    "expressions": ("expressions", False),
    "styles": ("styles", False),
}

PACKAGE = "mplchart"
OUTPUT_DIR = Path(__file__).parent.parent / "docs" / "reference"

# public members to leave out of the reference (qualified within their page)
EXCLUDE = {
    "Chart.plot_indicator",
    "Chart.plot_vline",
    "Chart.view",
    "Chart.mapper",
    "Chart.init_prices",
    "Chart.get_view",
}

MARKER = "<!-- generated by scripts/make-api-docs.py — do not edit -->"

# llms.txt — published at the site root by mkdocs (non-md files copy verbatim);
# links point at the raw markdown in the repo, which llms.txt moves with atomically
RAW_BASE = "https://raw.githubusercontent.com/furechan/mplchart/main/docs"

LLMS_INTRO = """\
# mplchart

Classic technical analysis stock charts in Python, built on matplotlib.

This site is rendered HTML for humans. The markdown sources below are
better suited for LLM consumption.
"""

# hand-written pages to list in llms.txt (docs-relative path -> summary)
LLMS_REFERENCE_EXTRAS = {
    "reference/index.md": "Reference overview and conventions",
}

LLMS_GUIDES = {
    "backends.md": "pandas and polars data pipelines",
}

# markdown extensions used by mkdocs (see mkdocs.yml), for the verify step
MKDOCS_EXTENSIONS = ["admonition", "pymdownx.highlight", "pymdownx.superfences"]


def clean_type(text: str) -> str:
    text = re.sub(r"\bOptional\[Literal\[(.+?)\]\]", r"Literal[\1] | None", text)
    return text


def clean_prose(text: str) -> str:
    """Convert residual RST markup in docstring prose to plain markdown"""
    text = re.sub(r":(?:func|class|meth|mod|attr):`~?([^`]+)`", r"`\1`", text)
    text = re.sub(r"::$", ":", text, flags=re.MULTILINE)
    return text.replace("``", "`")


def format_signature(name: str, params) -> list[str]:
    parts = []
    saw_star = False
    for p in params:
        if p.name == "self":
            continue
        kind = p.kind.value if p.kind else "positional or keyword"
        if kind == "keyword-only" and not saw_star:
            parts.append("*")
            saw_star = True
        text = p.name
        if kind == "variadic positional":
            text = f"*{text}"
            saw_star = True
        elif kind == "variadic keyword":
            text = f"**{text}"
        if p.annotation is not None:
            text += f": {p.annotation}"
        if p.default is not None and kind not in (
            "variadic positional",
            "variadic keyword",
        ):
            text += f" = {p.default}" if p.annotation is not None else f"={p.default}"
        parts.append(text)
    joined = ", ".join(parts)
    line = clean_type(f"{name}({joined})")
    if len(line) <= 88:
        return ["```python", line, "```", ""]
    inner = [f"    {clean_type(part)}," for part in parts]
    return ["```python", f"{name}(", *inner, ")", "```", ""]


def render_field_list(title: str, items) -> list[str]:
    lines = [f"**{title}:**", ""]
    for item in items:
        name = getattr(item, "name", "") or ""
        annotation = getattr(item, "annotation", None)
        label = f"**{name}**" if name else ""
        if annotation is not None:
            label += f" ({clean_type(str(annotation))})"
        description = clean_prose(item.description.strip())
        lines.append(f"- {label}: {description}" if label else f"- {description}")
    lines.append("")
    return lines


def render_docstring(docstring) -> list[str]:
    if docstring is None:
        return []
    lines = []
    for section in docstring.parsed:
        kind = section.kind.value
        if kind == "text":
            lines += [clean_prose(section.value.strip()), ""]
        elif kind == "parameters":
            lines += render_field_list("Arguments", section.value)
        elif kind == "other parameters":
            lines += render_field_list("Other arguments", section.value)
        elif kind == "attributes":
            lines += render_field_list("Attributes", section.value)
        elif kind == "returns":
            lines += render_field_list("Returns", section.value)
        elif kind == "yields":
            lines += render_field_list("Yields", section.value)
        elif kind == "raises":
            lines += render_field_list("Raises", section.value)
        elif kind == "examples":
            lines += ["**Examples:**", "", "```python"]
            for _, text in section.value:
                lines.append(text.strip())
            lines += ["```", ""]
        else:
            value = getattr(section, "value", None)
            text = value if isinstance(value, str) else str(value)
            lines += [clean_prose(text.strip()), ""]
    return lines


def is_property(member) -> bool:
    return member.is_attribute and "property" in member.labels


def render_class(cls, *, with_members: bool) -> list[str]:
    lines = [f"### {cls.name}", ""]
    lines += format_signature(cls.name, cls.parameters)
    lines += render_docstring(cls.docstring)
    if not with_members:
        return lines
    for m in cls.members.values():
        if m.name.startswith("_") or f"{cls.name}.{m.name}" in EXCLUDE:
            continue
        if m.is_function:
            lines += [f"#### {cls.name}.{m.name}", ""]
            lines += format_signature(m.name, m.parameters)
            lines += render_docstring(m.docstring)
        elif m.is_attribute and m.docstring:
            lines += [f"#### {cls.name}.{m.name}", ""]
            lines += render_docstring(m.docstring)
    return lines


def public_members(mod) -> list:
    """Exported members in __all__ order, or own members in source order."""
    exports = mod.exports
    if exports and all(isinstance(e, str) for e in exports):
        return [mod.members[name] for name in exports if name in mod.members]
    return [
        m
        for m in mod.members.values()
        if not m.name.startswith("_") and not m.is_alias and not m.is_module
    ]


def render_module(mod, *, class_members: bool = False) -> str:
    lines = [MARKER, "", f"# {PACKAGE}.{mod.name}", ""]
    lines += render_docstring(mod.docstring)
    lines += ["---", ""]

    for m in public_members(mod):
        if m.is_alias:
            m = m.final_target
        if m.is_class:
            lines += render_class(m, with_members=class_members)
        elif m.is_function:
            lines += [f"### {m.name}", ""]
            lines += format_signature(m.name, m.parameters)
            lines += render_docstring(m.docstring)
        elif m.is_attribute:
            lines += [f"### {m.name}", ""]
            if m.annotation is not None:
                lines += [f"`{m.name}: {clean_type(str(m.annotation))}`", ""]
            lines += render_docstring(m.docstring)

    return "\n".join(lines)


def verify(name: str, text: str) -> list[str]:
    """Check the generated markdown renders cleanly under mkdocs' parser."""
    problems = []
    if text.count("```") % 2:
        problems.append("unbalanced code fence")
    html = markdown.markdown(text, extensions=MKDOCS_EXTENSIONS)
    for para in html.split("<p>"):
        if re.search(r"\n\s*- ", para.split("</p>")[0]):
            problems.append("list trapped inside a paragraph")
            break
    return [f"{name}.md: {p}" for p in problems]


def write_llms_txt(package) -> None:
    lines = [LLMS_INTRO, "## API reference", ""]
    for module_path, (stem, _) in MODULES.items():
        docstring = package[module_path].docstring
        summary = (
            clean_prose(docstring.value.split("\n")[0].rstrip(".")) if docstring else ""
        )
        lines.append(
            f"- [{PACKAGE}.{module_path}]({RAW_BASE}/reference/{stem}.md): {summary}"
        )
    for page, summary in LLMS_REFERENCE_EXTRAS.items():
        lines.append(f"- [{Path(page).stem}]({RAW_BASE}/{page}): {summary}")
    lines += ["", "## Guides", ""]
    for page, summary in LLMS_GUIDES.items():
        lines.append(f"- [{Path(page).stem}]({RAW_BASE}/{page}): {summary}")
    lines.append("")
    path = OUTPUT_DIR.parent / "llms.txt"
    path.write_text("\n".join(lines))
    print(f"  -> {path}")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    package = griffe.load(PACKAGE, docstring_parser="google")

    problems = []
    for module_path, (stem, class_members) in MODULES.items():
        print(f"Generating {PACKAGE}.{module_path} ...")
        content = render_module(package[module_path], class_members=class_members)
        problems += verify(stem, content)
        output_path = OUTPUT_DIR / f"{stem}.md"
        output_path.write_text(content)
        print(f"  -> {output_path}")

    write_llms_txt(package)

    if problems:
        print("\nRender check FAILED:", *problems, sep="\n  ")
        sys.exit(1)


if __name__ == "__main__":
    main()
